import { StyleSheet } from "react-native";

export const fonts = {
  display: "ZillaSlab_700Bold",
  regular: "ZillaSlab_400Regular",
  bold: "ZillaSlab_600SemiBold",
  extraBold: "BarlowCondensed_600SemiBold",
  black: "BarlowCondensed_800ExtraBold",
  accent: "Caveat_600SemiBold",
};

export type ThemeMode = "light" | "dark";

export interface ThemePalette {
  bg: string;
  bgDeep: string;
  surface: string;
  surfaceStrong: string;
  text: string;
  muted: string;
  border: string;
  primary: string;
  secondary: string;
  secondaryStrong: string;
  accent: string;
  danger: string;
  dangerBg: string;
  success: string;
  successBg: string;
  cat: string;
  dog: string;
}


export const palette: Record<ThemeMode, ThemePalette> = {
  light: {
    bg: "#dee3dc",
    bgDeep: "#d9cfae",
    surface: "rgba(250, 248, 245, 0.97)",
    surfaceStrong: "#fbfaf9",
    text: "#3a2e22",
    muted: "#6b5f4f",
    border: "rgba(58, 45, 26, 0.18)",
    primary: "#b5401c",
    secondary: "#3f6b4a",
    secondaryStrong: "#20402b",
    accent: "#c99a35",
    danger: "#9c2a10",
    dangerBg: "rgba(156, 42, 16, 0.13)",
    success: "#20402b",
    successBg: "rgba(63, 107, 74, 0.15)",
    cat: "#a85c82",
    dog: "#5f7a3f",
  },
  dark: {
    bg: "#11271d",
    bgDeep: "#08160f",
    surface: "rgba(30, 38, 33, 0.94)",
    surfaceStrong: "#2b342f",
    text: "#f1e6d2",
    muted: "#bda98c",
    border: "rgba(241, 230, 210, 0.14)",
    primary: "#e17a4a",
    secondary: "#7fa87f",
    secondaryStrong: "#a8cf9e",
    accent: "#e0b45a",
    danger: "#ff9068",
    dangerBg: "rgba(255, 120, 80, 0.16)",
    success: "#a8cf9e",
    successBg: "rgba(127, 168, 127, 0.18)",
    cat: "#d888ab",
    dog: "#9bc078",
  },
};


export function createStyles(theme: ThemePalette) {
  return StyleSheet.create({
    root: {
      flex: 1,
      backgroundColor: theme.bg,
    },
    content: {
      paddingHorizontal: 16,
    },
    heroCard: {
      padding: 18,
      paddingTop: 22,
      borderRadius: 10,
      backgroundColor: theme.surface,
      borderWidth: 1,
      borderColor: theme.border,
      position: "relative",
      transform: [{ rotate: "-0.5deg" }],
      shadowColor: theme.text,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.16,
      shadowRadius: 8,
      elevation: 3,
    },
    pinDot: {
      position: "absolute",
      top: -9,
      left: "50%",
      marginLeft: -9,
      width: 18,
      height: 18,
      borderRadius: 9,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: theme.primary,
      borderWidth: 2,
      borderColor: theme.surfaceStrong,
      shadowColor: theme.text,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.3,
      shadowRadius: 2,
      elevation: 4,
      zIndex: 2,
    },
    pinDotUrgent: {
      left: 18,
      marginLeft: 0,
      backgroundColor: theme.danger,
    },
    eyebrow: {
      color: theme.primary,
      fontSize: 12,
      fontFamily: fonts.black,
      textTransform: "uppercase",
      letterSpacing: 1,
      marginBottom: 8,
    },
    heroTitle: {
      color: theme.text,
      fontSize: 30,
      lineHeight: 35,
      fontFamily: fonts.display,
      marginBottom: 10,
    },
    bodyText: {
      color: theme.muted,
      fontSize: 15,
      lineHeight: 23,
      fontFamily: fonts.regular,
    },
    actionRow: {
      flexDirection: "row",
      flexWrap: "wrap",
      marginTop: 16,
    },
    button: {
      minHeight: 44,
      borderRadius: 10,
      paddingHorizontal: 16,
      marginRight: 10,
      marginBottom: 10,
      backgroundColor: theme.primary,
      borderWidth: 1,
      borderColor: theme.primary,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      maxWidth: "100%",
    },
    buttonSecondary: {
      backgroundColor: `${theme.secondary}26`,
      borderColor: `${theme.secondary}55`,
    },
    buttonCompact: {
      marginRight: 0,
      alignSelf: "flex-start",
    },
    buttonPressed: {
      opacity: 0.82,
    },
    buttonText: {
      color: "#fffaf7",
      fontFamily: fonts.black,
      marginLeft: 6,
      flexShrink: 1,
    },
    buttonSecondaryText: {
      color: theme.secondaryStrong,
    },
    activityPanel: {
      marginTop: 16,
      borderRadius: 18,
      backgroundColor: theme.surface,
      borderWidth: 1,
      borderColor: theme.border,
      padding: 14,
    },
    activityHeader: {
      marginBottom: 10,
    },
    activityTitle: {
      color: theme.text,
      fontSize: 18,
      fontFamily: fonts.display,
      marginBottom: 4,
    },
    activityDescription: {
      color: theme.muted,
      fontSize: 13,
      lineHeight: 19,
      fontFamily: fonts.bold,
    },
    activityRow: {
      minHeight: 72,
      borderRadius: 14,
      backgroundColor: theme.surfaceStrong,
      borderWidth: 1,
      borderColor: theme.border,
      padding: 12,
      marginTop: 8,
      flexDirection: "row",
      alignItems: "center",
    },
    activityRowUrgent: {
      backgroundColor: theme.dangerBg,
      borderColor: `${theme.danger}55`,
      borderRadius: 10,
      position: "relative",
      marginTop: 14,
      transform: [{ rotate: "-1.2deg" }],
      shadowColor: theme.text,
      shadowOffset: { width: 0, height: 3 },
      shadowOpacity: 0.18,
      shadowRadius: 5,
      elevation: 3,
    },
    activityIcon: {
      width: 38,
      height: 38,
      borderRadius: 19,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: `${theme.secondary}22`,
      marginRight: 12,
    },
    activityIconUrgent: {
      backgroundColor: `${theme.danger}22`,
    },
    activityText: {
      flex: 1,
      paddingRight: 8,
    },
    activityLabel: {
      color: theme.secondaryStrong,
      fontSize: 12,
      fontFamily: fonts.black,
      letterSpacing: 0.6,
      marginBottom: 2,
    },
    activityLabelUrgent: {
      color: theme.danger,
      fontFamily: fonts.accent,
      fontSize: 19,
      letterSpacing: 0,
      marginBottom: -2,
    },
    activityItemTitle: {
      color: theme.text,
      fontSize: 16,
      fontFamily: fonts.black,
    },
    activityDetail: {
      color: theme.muted,
      fontSize: 12,
      lineHeight: 17,
      fontFamily: fonts.bold,
      marginTop: 2,
    },
    sectionHeader: {
      marginBottom: 14,
    },
    sectionText: {
      marginBottom: 12,
    },
    sectionTitle: {
      color: theme.text,
      fontSize: 28,
      fontFamily: fonts.display,
      marginBottom: 8,
    },
    cardStack: {
      paddingBottom: 10,
    },
    feedInsight: {
      borderRadius: 16,
      backgroundColor: theme.surface,
      borderWidth: 1,
      borderColor: theme.border,
      padding: 14,
      marginBottom: 14,
      flexDirection: "row",
      alignItems: "center",
    },
    feedInsightCompact: {
      minHeight: 54,
      paddingVertical: 10,
    },
    feedInsightUrgent: {
      backgroundColor: theme.dangerBg,
      borderColor: `${theme.danger}55`,
    },
    feedInsightIcon: {
      width: 42,
      height: 42,
      borderRadius: 21,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: `${theme.secondary}22`,
      marginRight: 12,
    },
    feedInsightIconUrgent: {
      backgroundColor: `${theme.danger}22`,
    },
    feedInsightText: {
      flex: 1,
    },
    feedInsightLabel: {
      color: theme.secondaryStrong,
      fontSize: 12,
      fontFamily: fonts.black,
      marginBottom: 2,
    },
    feedInsightLabelUrgent: {
      color: theme.danger,
    },
    feedInsightValue: {
      color: theme.text,
      fontSize: 18,
      fontFamily: fonts.black,
      marginBottom: 2,
    },
    feedInsightDetail: {
      color: theme.muted,
      fontSize: 13,
      lineHeight: 18,
      fontFamily: fonts.bold,
    },
    feedStatus: {
      minHeight: 44,
      borderRadius: 14,
      borderWidth: 1,
      borderColor: theme.border,
      backgroundColor: theme.surfaceStrong,
      paddingHorizontal: 12,
      marginBottom: 14,
      flexDirection: "row",
      alignItems: "center",
    },
    feedStatusText: {
      color: theme.muted,
      flex: 1,
      fontSize: 13,
      fontFamily: fonts.extraBold,
      marginLeft: 8,
    },
    feedStatusAction: {
      minHeight: 36,
      justifyContent: "center",
      paddingLeft: 10,
    },
    feedStatusActionText: {
      color: theme.secondaryStrong,
      fontFamily: fonts.black,
    },
    filterToggle: {
      minHeight: 48,
      borderRadius: 14,
      backgroundColor: theme.surface,
      borderWidth: 1,
      borderColor: theme.border,
      paddingHorizontal: 12,
      marginBottom: 14,
      flexDirection: "row",
      alignItems: "center",
    },
    filterToggleActive: {
      backgroundColor: theme.surfaceStrong,
      borderColor: `${theme.secondary}55`,
    },
    filterToggleIcon: {
      width: 34,
      height: 34,
      borderRadius: 17,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: `${theme.secondary}22`,
      marginRight: 10,
    },
    filterToggleText: {
      flex: 1,
      paddingRight: 10,
    },
    filterToggleLabel: {
      color: theme.text,
      fontFamily: fonts.black,
    },
    filterToggleBadge: {
      color: theme.secondaryStrong,
      fontSize: 12,
      fontFamily: fonts.extraBold,
      marginTop: 2,
    },
    filterPanel: {
      borderRadius: 18,
      backgroundColor: theme.surface,
      borderWidth: 1,
      borderColor: theme.border,
      padding: 14,
      marginBottom: 14,
      position: "relative",
    },
    filterPanelClose: {
      position: "absolute",
      top: 10,
      right: 10,
      zIndex: 2,
      width: 32,
      height: 32,
      borderRadius: 16,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: theme.surfaceStrong,
      borderWidth: 1,
      borderColor: theme.border,
    },
    filterGroup: {
      marginBottom: 12,
    },
    filterLabel: {
      color: theme.text,
      fontFamily: fonts.black,
      fontSize: 13,
      marginBottom: 8,
    },
    segmentedControl: {
      flexDirection: "row",
      backgroundColor: theme.surfaceStrong,
      borderRadius: 14,
      borderWidth: 1,
      borderColor: theme.border,
      padding: 4,
    },
    segmentButton: {
      flex: 1,
      minHeight: 44,
      borderRadius: 11,
      alignItems: "center",
      justifyContent: "center",
      flexDirection: "row",
      paddingHorizontal: 8,
    },
    segmentButtonActive: {
      backgroundColor: `${theme.accent}24`,
    },
    segmentText: {
      color: theme.muted,
      fontFamily: fonts.black,
      fontSize: 12,
      marginLeft: 5,
      flexShrink: 1,
      textAlign: "center",
    },
    segmentTextSolo: {
      marginLeft: 0,
    },
    segmentTextActive: {
      color: theme.text,
    },
    filterInputWrap: {
      minHeight: 46,
      borderRadius: 14,
      borderWidth: 1,
      borderColor: theme.border,
      backgroundColor: theme.surfaceStrong,
      paddingHorizontal: 12,
      flexDirection: "row",
      alignItems: "center",
    },
    filterInput: {
      flex: 1,
      color: theme.text,
      fontFamily: fonts.extraBold,
      paddingVertical: 10,
      paddingLeft: 8,
    },
    clearFiltersButton: {
      alignSelf: "flex-start",
      minHeight: 44,
      paddingHorizontal: 2,
      paddingTop: 2,
      flexDirection: "row",
      alignItems: "center",
    },
    clearFiltersText: {
      color: theme.muted,
      fontFamily: fonts.extraBold,
      fontSize: 12,
      marginLeft: 4,
    },
    currentLocationButton: {
      minHeight: 44,
      alignSelf: "flex-start",
      borderRadius: 14,
      borderWidth: 1,
      borderColor: `${theme.secondary}55`,
      backgroundColor: `${theme.secondary}18`,
      paddingHorizontal: 12,
      marginBottom: 12,
      flexDirection: "row",
      alignItems: "center",
    },
    currentLocationText: {
      color: theme.secondaryStrong,
      fontFamily: fonts.black,
      marginLeft: 6,
    },
    suggestionList: {
      maxHeight: 220,
      borderRadius: 14,
      borderWidth: 1,
      borderColor: theme.border,
      backgroundColor: theme.surfaceStrong,
      marginTop: 8,
      overflow: "hidden",
    },
    suggestionItem: {
      minHeight: 44,
      paddingHorizontal: 12,
      flexDirection: "row",
      alignItems: "center",
      borderBottomWidth: 1,
      borderBottomColor: theme.border,
    },
    suggestionText: {
      color: theme.text,
      fontFamily: fonts.extraBold,
      marginLeft: 8,
    },
    emptyState: {
      borderRadius: 18,
      borderWidth: 1,
      borderColor: theme.border,
      backgroundColor: theme.surface,
      padding: 18,
      alignItems: "center",
      justifyContent: "center",
    },
    emptyText: {
      color: theme.muted,
      fontFamily: fonts.black,
      textAlign: "center",
      marginTop: 8,
    },
    petCard: {
      borderRadius: 18,
      overflow: "hidden",
      backgroundColor: theme.surface,
      borderWidth: 1,
      borderColor: theme.border,
      marginBottom: 14,
    },
    petImage: {
      width: "100%",
      aspectRatio: 3 / 4,
      backgroundColor: theme.bgDeep,
    },
    petContent: {
      padding: 16,
    },
    speciesIcon: {
      position: "absolute",
      right: 14,
      bottom: 14,
      width: 44,
      height: 44,
      borderRadius: 22,
      alignItems: "center",
      justifyContent: "center",
      opacity: 0.9,
    },
    cardMeta: {
      color: theme.muted,
      fontSize: 13,
      fontFamily: fonts.extraBold,
      marginBottom: 6,
    },
    cardTitle: {
      color: theme.text,
      fontSize: 22,
      fontFamily: fonts.display,
      marginBottom: 8,
      paddingRight: 42,
    },
    cardDescription: {
      color: theme.muted,
      fontSize: 15,
      lineHeight: 23,
      marginBottom: 12,
      paddingRight: 34,
      fontFamily: fonts.regular,
    },
    metaLine: {
      color: theme.secondaryStrong,
      flexDirection: "row",
      alignItems: "center",
      marginBottom: 8,
    },
    metaText: {
      color: theme.muted,
      fontFamily: fonts.extraBold,
      marginLeft: 6,
      flex: 1,
    },
    contactText: {
      color: theme.text,
      fontFamily: fonts.black,
      paddingRight: 44,
    },
    badge: {
      alignSelf: "flex-start",
      borderRadius: 999,
      paddingHorizontal: 10,
      paddingVertical: 5,
      backgroundColor: `${theme.secondary}28`,
      marginRight: 6,
      marginBottom: 6,
    },
    badgeUrgent: {
      backgroundColor: theme.dangerBg,
      borderWidth: 1,
      borderColor: `${theme.danger}55`,
    },
    badgeText: {
      color: theme.secondaryStrong,
      fontFamily: fonts.black,
      fontSize: 12,
    },
    badgeUrgentText: {
      color: theme.danger,
    },
    tagRow: {
      flexDirection: "row",
      flexWrap: "wrap",
      paddingRight: 44,
    },
    settingsPanel: {
      borderRadius: 18,
      backgroundColor: theme.surface,
      borderWidth: 1,
      borderColor: theme.border,
      padding: 14,
      marginBottom: 14,
    },
    settingsGroupTitle: {
      color: theme.muted,
      fontFamily: fonts.black,
      fontSize: 12,
      textTransform: "uppercase",
      marginBottom: 10,
    },
    settingsUserHeader: {
      flexDirection: "row",
      alignItems: "center",
      marginBottom: 10,
    },
    settingsAvatar: {
      width: 48,
      height: 48,
      borderRadius: 24,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: theme.secondaryStrong,
      marginRight: 12,
    },
    settingsUserText: {
      flex: 1,
    },
    settingsRow: {
      minHeight: 54,
      borderRadius: 14,
      backgroundColor: theme.surfaceStrong,
      borderWidth: 1,
      borderColor: theme.border,
      paddingHorizontal: 12,
      marginTop: 10,
      flexDirection: "row",
      alignItems: "center",
    },
    settingsIcon: {
      width: 34,
      height: 34,
      borderRadius: 17,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: `${theme.secondary}22`,
      marginRight: 10,
    },
    settingsRowContent: {
      flex: 1,
    },
    settingsRowLabel: {
      color: theme.text,
      fontFamily: fonts.black,
      fontSize: 14,
    },
    settingsRowValue: {
      color: theme.muted,
      fontFamily: fonts.bold,
      fontSize: 12,
      marginTop: 2,
      flexShrink: 1,
    },
    tabBar: {
      position: "absolute",
      left: 12,
      right: 12,
      borderRadius: 14,
      padding: 6,
      backgroundColor: theme.surface,
      borderWidth: 1,
      borderColor: theme.border,
      flexDirection: "row",
    },
    tabItem: {
      flex: 1,
      alignItems: "center",
      borderRadius: 10,
      paddingVertical: 6,
      paddingHorizontal: 2,
    },
    tabItemActive: {
      backgroundColor: `${theme.accent}24`,
    },
    tabText: {
      color: theme.muted,
      fontFamily: fonts.extraBold,
      fontSize: 11,
      marginTop: 2,
      textAlign: "center",
    },
    tabTextActive: {
      color: theme.text,
    },
    modalBackdrop: {
      flex: 1,
      justifyContent: "flex-end",
    },
    modalScrim: {
      position: "absolute",
      top: 0,
      right: 0,
      bottom: 0,
      left: 0,
      backgroundColor: "rgba(0, 0, 0, 0.42)",
    },
    modalSheetWrap: {
      width: "100%",
    },
    modalCard: {
      borderTopLeftRadius: 26,
      borderTopRightRadius: 26,
      padding: 20,
      paddingBottom: 34,
      backgroundColor: theme.surfaceStrong,
      borderWidth: 1,
      borderColor: theme.border,
    },
    modalIcon: {
      width: 56,
      height: 56,
      borderRadius: 28,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: `${theme.secondary}24`,
      marginBottom: 12,
    },
    profileHeader: {
      flexDirection: "row",
      alignItems: "center",
      marginBottom: 12,
    },
    profileAvatar: {
      width: 56,
      height: 56,
      borderRadius: 28,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: theme.secondaryStrong,
      marginRight: 12,
    },
    profileIdentity: {
      flex: 1,
    },
    profileName: {
      color: theme.text,
      fontFamily: fonts.black,
      fontSize: 15,
    },
    profileEmail: {
      color: theme.muted,
      fontFamily: fonts.bold,
      marginTop: 2,
    },
    profileOptions: {
      marginTop: 14,
    },
    profileRow: {
      minHeight: 48,
      borderRadius: 14,
      borderWidth: 1,
      borderColor: theme.border,
      backgroundColor: theme.surface,
      paddingHorizontal: 14,
      marginBottom: 10,
      flexDirection: "row",
      alignItems: "center",
    },
    profileRowText: {
      flex: 1,
      color: theme.text,
      fontFamily: fonts.black,
      marginLeft: 10,
    },
    modalTitle: {
      color: theme.text,
      fontSize: 24,
      fontFamily: fonts.display,
      marginBottom: 8,
    },
    modalActions: {
      flexDirection: "row",
      flexWrap: "wrap",
      marginTop: 16,
    },
    input: {
      minHeight: 46,
      borderRadius: 14,
      borderWidth: 1,
      borderColor: theme.border,
      backgroundColor: theme.surface,
      color: theme.text,
      paddingHorizontal: 14,
      marginTop: 10,
      fontFamily: fonts.regular,
    },
    formField: {
      marginTop: 12,
    },
    formLabel: {
      color: theme.text,
      fontFamily: fonts.black,
      fontSize: 13,
      marginBottom: 6,
    },
    inputError: {
      borderColor: theme.danger,
      backgroundColor: theme.dangerBg,
    },
    fieldError: {
      color: theme.danger,
      fontFamily: fonts.extraBold,
      fontSize: 12,
      marginTop: 6,
    },
    formErrorSummary: {
      color: theme.danger,
      fontFamily: fonts.black,
      marginTop: 12,
    },
    formSuccess: {
      color: theme.success,
      backgroundColor: theme.successBg,
      borderWidth: 1,
      borderColor: `${theme.success}55`,
      borderRadius: 14,
      paddingHorizontal: 12,
      paddingVertical: 10,
      fontFamily: fonts.black,
      marginTop: 12,
    },
    textArea: {
      minHeight: 94,
      paddingTop: 12,
      textAlignVertical: "top",
    },
  });
}
