import { StyleSheet } from "react-native";

export type ThemeMode = "light" | "dark";

export interface ThemePalette {
  bg: string;
  bgDeep: string;
  surface: string;
  surfaceStrong: string;
  text: string;
  muted: string;
  border: string;
  primary: string;
  secondary: string;
  secondaryStrong: string;
  accent: string;
  danger: string;
  dangerBg: string;
  success: string;
  successBg: string;
  cat: string;
  dog: string;
  pawOpacity: number;
}


export const palette: Record<ThemeMode, ThemePalette> = {
  light: {
    bg: "#edf2df",
    bgDeep: "#cbd9bc",
    surface: "rgba(255, 252, 243, 0.94)",
    surfaceStrong: "#fffaf0",
    text: "#28342a",
    muted: "#687060",
    border: "rgba(65, 82, 56, 0.16)",
    primary: "#a94f31",
    secondary: "#477454",
    secondaryStrong: "#254c35",
    accent: "#d8a13a",
    danger: "#9f3030",
    dangerBg: "rgba(159, 48, 48, 0.13)",
    success: "#254c35",
    successBg: "rgba(71, 116, 84, 0.15)",
    cat: "#df8ab4",
    dog: "#6d8e50",
    pawOpacity: 1,
  },
  dark: {
    bg: "#0d2b1b",
    bgDeep: "#07190f",
    surface: "rgba(25, 35, 29, 0.94)",
    surfaceStrong: "#233229",
    text: "#efe8db",
    muted: "#b8b09f",
    border: "rgba(239, 232, 219, 0.12)",
    primary: "#eb916d",
    secondary: "#82ad76",
    secondaryStrong: "#a7d696",
    accent: "#e1b95b",
    danger: "#ffb0a5",
    dangerBg: "rgba(255, 128, 112, 0.16)",
    success: "#a7d696",
    successBg: "rgba(130, 173, 118, 0.18)",
    cat: "#f1a1c5",
    dog: "#a9c979",
    pawOpacity: 0.1,
  },
};


export function createStyles(theme: ThemePalette) {
  return StyleSheet.create({
    root: {
      flex: 1,
      backgroundColor: theme.bg,
    },
    backgroundPaw: {
      position: "absolute",
      width: 168,
      height: 168,
      opacity: theme.pawOpacity,
    },
    backgroundPawImage: {
      resizeMode: "contain",
    },
    content: {
      padding: 16,
      paddingTop: 64,
      paddingBottom: 110,
    },
    heroCard: {
      padding: 18,
      borderRadius: 18,
      backgroundColor: theme.surface,
      borderWidth: 1,
      borderColor: theme.border,
    },
    eyebrow: {
      color: theme.primary,
      fontSize: 12,
      fontWeight: "900",
      textTransform: "uppercase",
      marginBottom: 8,
    },
    heroTitle: {
      color: theme.text,
      fontSize: 30,
      lineHeight: 35,
      fontWeight: "900",
      marginBottom: 10,
    },
    bodyText: {
      color: theme.muted,
      fontSize: 15,
      lineHeight: 23,
    },
    actionRow: {
      flexDirection: "row",
      flexWrap: "wrap",
      marginTop: 16,
    },
    button: {
      minHeight: 44,
      borderRadius: 22,
      paddingHorizontal: 16,
      marginRight: 10,
      marginBottom: 10,
      backgroundColor: theme.primary,
      borderWidth: 1,
      borderColor: theme.primary,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      maxWidth: "100%",
    },
    buttonSecondary: {
      backgroundColor: `${theme.secondary}26`,
      borderColor: `${theme.secondary}55`,
    },
    buttonCompact: {
      marginRight: 0,
      alignSelf: "flex-start",
    },
    buttonPressed: {
      opacity: 0.82,
    },
    buttonText: {
      color: "#fffaf7",
      fontWeight: "900",
      marginLeft: 6,
      flexShrink: 1,
    },
    buttonSecondaryText: {
      color: theme.secondaryStrong,
    },
    activityPanel: {
      marginTop: 16,
      borderRadius: 18,
      backgroundColor: theme.surface,
      borderWidth: 1,
      borderColor: theme.border,
      padding: 14,
    },
    activityHeader: {
      marginBottom: 10,
    },
    activityTitle: {
      color: theme.text,
      fontSize: 18,
      fontWeight: "900",
      marginBottom: 4,
    },
    activityDescription: {
      color: theme.muted,
      fontSize: 13,
      lineHeight: 19,
      fontWeight: "700",
    },
    activityRow: {
      minHeight: 72,
      borderRadius: 14,
      backgroundColor: theme.surfaceStrong,
      borderWidth: 1,
      borderColor: theme.border,
      padding: 12,
      marginTop: 8,
      flexDirection: "row",
      alignItems: "center",
    },
    activityRowUrgent: {
      backgroundColor: theme.dangerBg,
      borderColor: `${theme.danger}55`,
    },
    activityIcon: {
      width: 38,
      height: 38,
      borderRadius: 19,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: `${theme.secondary}22`,
      marginRight: 12,
    },
    activityIconUrgent: {
      backgroundColor: `${theme.danger}22`,
    },
    activityText: {
      flex: 1,
      paddingRight: 8,
    },
    activityLabel: {
      color: theme.secondaryStrong,
      fontSize: 12,
      fontWeight: "900",
      marginBottom: 2,
    },
    activityLabelUrgent: {
      color: theme.danger,
    },
    activityItemTitle: {
      color: theme.text,
      fontSize: 16,
      fontWeight: "900",
    },
    activityDetail: {
      color: theme.muted,
      fontSize: 12,
      lineHeight: 17,
      fontWeight: "700",
      marginTop: 2,
    },
    sectionHeader: {
      marginBottom: 14,
    },
    sectionText: {
      marginBottom: 12,
    },
    sectionTitle: {
      color: theme.text,
      fontSize: 28,
      fontWeight: "900",
      marginBottom: 8,
    },
    cardStack: {
      paddingBottom: 10,
    },
    feedInsight: {
      borderRadius: 16,
      backgroundColor: theme.surface,
      borderWidth: 1,
      borderColor: theme.border,
      padding: 14,
      marginBottom: 14,
      flexDirection: "row",
      alignItems: "center",
    },
    feedInsightCompact: {
      minHeight: 54,
      paddingVertical: 10,
    },
    feedInsightUrgent: {
      backgroundColor: theme.dangerBg,
      borderColor: `${theme.danger}55`,
    },
    feedInsightIcon: {
      width: 42,
      height: 42,
      borderRadius: 21,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: `${theme.secondary}22`,
      marginRight: 12,
    },
    feedInsightIconUrgent: {
      backgroundColor: `${theme.danger}22`,
    },
    feedInsightText: {
      flex: 1,
    },
    feedInsightLabel: {
      color: theme.secondaryStrong,
      fontSize: 12,
      fontWeight: "900",
      marginBottom: 2,
    },
    feedInsightLabelUrgent: {
      color: theme.danger,
    },
    feedInsightValue: {
      color: theme.text,
      fontSize: 18,
      fontWeight: "900",
      marginBottom: 2,
    },
    feedInsightDetail: {
      color: theme.muted,
      fontSize: 13,
      lineHeight: 18,
      fontWeight: "700",
    },
    feedStatus: {
      minHeight: 44,
      borderRadius: 14,
      borderWidth: 1,
      borderColor: theme.border,
      backgroundColor: theme.surfaceStrong,
      paddingHorizontal: 12,
      marginBottom: 14,
      flexDirection: "row",
      alignItems: "center",
    },
    feedStatusText: {
      color: theme.muted,
      flex: 1,
      fontSize: 13,
      fontWeight: "800",
      marginLeft: 8,
    },
    feedStatusAction: {
      minHeight: 36,
      justifyContent: "center",
      paddingLeft: 10,
    },
    feedStatusActionText: {
      color: theme.secondaryStrong,
      fontWeight: "900",
    },
    filterToggle: {
      minHeight: 48,
      borderRadius: 14,
      backgroundColor: theme.surface,
      borderWidth: 1,
      borderColor: theme.border,
      paddingHorizontal: 12,
      marginBottom: 14,
      flexDirection: "row",
      alignItems: "center",
    },
    filterToggleActive: {
      backgroundColor: theme.surfaceStrong,
      borderColor: `${theme.secondary}55`,
    },
    filterToggleIcon: {
      width: 34,
      height: 34,
      borderRadius: 17,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: `${theme.secondary}22`,
      marginRight: 10,
    },
    filterToggleText: {
      flex: 1,
      paddingRight: 10,
    },
    filterToggleLabel: {
      color: theme.text,
      fontWeight: "900",
    },
    filterToggleBadge: {
      color: theme.secondaryStrong,
      fontSize: 12,
      fontWeight: "800",
      marginTop: 2,
    },
    filterPanel: {
      borderRadius: 18,
      backgroundColor: theme.surface,
      borderWidth: 1,
      borderColor: theme.border,
      padding: 14,
      marginBottom: 14,
      position: "relative",
    },
    filterPanelClose: {
      position: "absolute",
      top: 10,
      right: 10,
      zIndex: 2,
      width: 32,
      height: 32,
      borderRadius: 16,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: theme.surfaceStrong,
      borderWidth: 1,
      borderColor: theme.border,
    },
    filterGroup: {
      marginBottom: 12,
    },
    filterLabel: {
      color: theme.text,
      fontWeight: "900",
      fontSize: 13,
      marginBottom: 8,
    },
    segmentedControl: {
      flexDirection: "row",
      backgroundColor: theme.surfaceStrong,
      borderRadius: 14,
      borderWidth: 1,
      borderColor: theme.border,
      padding: 4,
    },
    segmentButton: {
      flex: 1,
      minHeight: 44,
      borderRadius: 11,
      alignItems: "center",
      justifyContent: "center",
      flexDirection: "row",
      paddingHorizontal: 8,
    },
    segmentButtonActive: {
      backgroundColor: `${theme.accent}24`,
    },
    segmentText: {
      color: theme.muted,
      fontWeight: "900",
      fontSize: 12,
      marginLeft: 5,
      flexShrink: 1,
      textAlign: "center",
    },
    segmentTextSolo: {
      marginLeft: 0,
    },
    segmentTextActive: {
      color: theme.text,
    },
    filterInputWrap: {
      minHeight: 46,
      borderRadius: 14,
      borderWidth: 1,
      borderColor: theme.border,
      backgroundColor: theme.surfaceStrong,
      paddingHorizontal: 12,
      flexDirection: "row",
      alignItems: "center",
    },
    filterInput: {
      flex: 1,
      color: theme.text,
      fontWeight: "800",
      paddingVertical: 10,
      paddingLeft: 8,
    },
    clearFiltersButton: {
      alignSelf: "flex-start",
      minHeight: 44,
      paddingHorizontal: 2,
      paddingTop: 2,
      flexDirection: "row",
      alignItems: "center",
    },
    clearFiltersText: {
      color: theme.muted,
      fontWeight: "800",
      fontSize: 12,
      marginLeft: 4,
    },
    currentLocationButton: {
      minHeight: 44,
      alignSelf: "flex-start",
      borderRadius: 14,
      borderWidth: 1,
      borderColor: `${theme.secondary}55`,
      backgroundColor: `${theme.secondary}18`,
      paddingHorizontal: 12,
      marginBottom: 12,
      flexDirection: "row",
      alignItems: "center",
    },
    currentLocationText: {
      color: theme.secondaryStrong,
      fontWeight: "900",
      marginLeft: 6,
    },
    suggestionList: {
      maxHeight: 220,
      borderRadius: 14,
      borderWidth: 1,
      borderColor: theme.border,
      backgroundColor: theme.surfaceStrong,
      marginTop: 8,
      overflow: "hidden",
    },
    suggestionItem: {
      minHeight: 44,
      paddingHorizontal: 12,
      flexDirection: "row",
      alignItems: "center",
      borderBottomWidth: 1,
      borderBottomColor: theme.border,
    },
    suggestionText: {
      color: theme.text,
      fontWeight: "800",
      marginLeft: 8,
    },
    emptyState: {
      borderRadius: 18,
      borderWidth: 1,
      borderColor: theme.border,
      backgroundColor: theme.surface,
      padding: 18,
      alignItems: "center",
      justifyContent: "center",
    },
    emptyText: {
      color: theme.muted,
      fontWeight: "900",
      textAlign: "center",
      marginTop: 8,
    },
    petCard: {
      borderRadius: 18,
      overflow: "hidden",
      backgroundColor: theme.surface,
      borderWidth: 1,
      borderColor: theme.border,
      marginBottom: 14,
    },
    petImage: {
      width: "100%",
      aspectRatio: 3 / 4,
      backgroundColor: theme.bgDeep,
    },
    petContent: {
      padding: 16,
    },
    speciesIcon: {
      position: "absolute",
      right: 14,
      bottom: 14,
      width: 44,
      height: 44,
      borderRadius: 22,
      alignItems: "center",
      justifyContent: "center",
      opacity: 0.9,
    },
    cardMeta: {
      color: theme.muted,
      fontSize: 13,
      fontWeight: "800",
      marginBottom: 6,
    },
    cardTitle: {
      color: theme.text,
      fontSize: 22,
      fontWeight: "900",
      marginBottom: 8,
      paddingRight: 42,
    },
    cardDescription: {
      color: theme.muted,
      fontSize: 15,
      lineHeight: 23,
      marginBottom: 12,
      paddingRight: 34,
    },
    metaLine: {
      color: theme.secondaryStrong,
      flexDirection: "row",
      alignItems: "center",
      marginBottom: 8,
    },
    metaText: {
      color: theme.muted,
      fontWeight: "800",
      marginLeft: 6,
      flex: 1,
    },
    contactText: {
      color: theme.text,
      fontWeight: "900",
      paddingRight: 44,
    },
    badge: {
      alignSelf: "flex-start",
      borderRadius: 999,
      paddingHorizontal: 10,
      paddingVertical: 5,
      backgroundColor: `${theme.secondary}28`,
      marginRight: 6,
      marginBottom: 6,
    },
    badgeUrgent: {
      backgroundColor: theme.dangerBg,
      borderWidth: 1,
      borderColor: `${theme.danger}55`,
    },
    badgeText: {
      color: theme.secondaryStrong,
      fontWeight: "900",
      fontSize: 12,
    },
    badgeUrgentText: {
      color: theme.danger,
    },
    tagRow: {
      flexDirection: "row",
      flexWrap: "wrap",
      paddingRight: 44,
    },
    settingsPanel: {
      borderRadius: 18,
      backgroundColor: theme.surface,
      borderWidth: 1,
      borderColor: theme.border,
      padding: 14,
      marginBottom: 14,
    },
    settingsGroupTitle: {
      color: theme.muted,
      fontWeight: "900",
      fontSize: 12,
      textTransform: "uppercase",
      marginBottom: 10,
    },
    settingsUserHeader: {
      flexDirection: "row",
      alignItems: "center",
      marginBottom: 10,
    },
    settingsAvatar: {
      width: 48,
      height: 48,
      borderRadius: 24,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: theme.secondaryStrong,
      marginRight: 12,
    },
    settingsUserText: {
      flex: 1,
    },
    settingsRow: {
      minHeight: 54,
      borderRadius: 14,
      backgroundColor: theme.surfaceStrong,
      borderWidth: 1,
      borderColor: theme.border,
      paddingHorizontal: 12,
      marginTop: 10,
      flexDirection: "row",
      alignItems: "center",
    },
    settingsIcon: {
      width: 34,
      height: 34,
      borderRadius: 17,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: `${theme.secondary}22`,
      marginRight: 10,
    },
    settingsRowContent: {
      flex: 1,
    },
    settingsRowLabel: {
      color: theme.text,
      fontWeight: "900",
      fontSize: 14,
    },
    settingsRowValue: {
      color: theme.muted,
      fontWeight: "700",
      fontSize: 12,
      marginTop: 2,
      flexShrink: 1,
    },
    tabBar: {
      position: "absolute",
      left: 12,
      right: 12,
      bottom: 18,
      borderRadius: 24,
      padding: 8,
      backgroundColor: theme.surface,
      borderWidth: 1,
      borderColor: theme.border,
      flexDirection: "row",
    },
    tabItem: {
      flex: 1,
      alignItems: "center",
      borderRadius: 18,
      paddingVertical: 8,
    },
    tabItemActive: {
      backgroundColor: `${theme.accent}24`,
    },
    tabText: {
      color: theme.muted,
      fontWeight: "800",
      fontSize: 11,
      marginTop: 3,
    },
    tabTextActive: {
      color: theme.text,
    },
    modalBackdrop: {
      flex: 1,
      justifyContent: "flex-end",
    },
    modalScrim: {
      position: "absolute",
      top: 0,
      right: 0,
      bottom: 0,
      left: 0,
      backgroundColor: "rgba(0, 0, 0, 0.42)",
    },
    modalSheetWrap: {
      width: "100%",
    },
    modalCard: {
      borderTopLeftRadius: 26,
      borderTopRightRadius: 26,
      padding: 20,
      paddingBottom: 34,
      backgroundColor: theme.surfaceStrong,
      borderWidth: 1,
      borderColor: theme.border,
    },
    modalIcon: {
      width: 56,
      height: 56,
      borderRadius: 28,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: `${theme.secondary}24`,
      marginBottom: 12,
    },
    profileHeader: {
      flexDirection: "row",
      alignItems: "center",
      marginBottom: 12,
    },
    profileAvatar: {
      width: 56,
      height: 56,
      borderRadius: 28,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: theme.secondaryStrong,
      marginRight: 12,
    },
    profileIdentity: {
      flex: 1,
    },
    profileName: {
      color: theme.text,
      fontWeight: "900",
      fontSize: 15,
    },
    profileEmail: {
      color: theme.muted,
      fontWeight: "700",
      marginTop: 2,
    },
    profileOptions: {
      marginTop: 14,
    },
    profileRow: {
      minHeight: 48,
      borderRadius: 14,
      borderWidth: 1,
      borderColor: theme.border,
      backgroundColor: theme.surface,
      paddingHorizontal: 14,
      marginBottom: 10,
      flexDirection: "row",
      alignItems: "center",
    },
    profileRowText: {
      flex: 1,
      color: theme.text,
      fontWeight: "900",
      marginLeft: 10,
    },
    modalTitle: {
      color: theme.text,
      fontSize: 24,
      fontWeight: "900",
      marginBottom: 8,
    },
    modalActions: {
      flexDirection: "row",
      flexWrap: "wrap",
      marginTop: 16,
    },
    input: {
      minHeight: 46,
      borderRadius: 14,
      borderWidth: 1,
      borderColor: theme.border,
      backgroundColor: theme.surface,
      color: theme.text,
      paddingHorizontal: 14,
      marginTop: 10,
    },
    formField: {
      marginTop: 12,
    },
    formLabel: {
      color: theme.text,
      fontWeight: "900",
      fontSize: 13,
      marginBottom: 6,
    },
    inputError: {
      borderColor: theme.danger,
      backgroundColor: theme.dangerBg,
    },
    fieldError: {
      color: theme.danger,
      fontWeight: "800",
      fontSize: 12,
      marginTop: 6,
    },
    formErrorSummary: {
      color: theme.danger,
      fontWeight: "900",
      marginTop: 12,
    },
    formSuccess: {
      color: theme.success,
      backgroundColor: theme.successBg,
      borderWidth: 1,
      borderColor: `${theme.success}55`,
      borderRadius: 14,
      paddingHorizontal: 12,
      paddingVertical: 10,
      fontWeight: "900",
      marginTop: 12,
    },
    textArea: {
      minHeight: 94,
      paddingTop: 12,
      textAlignVertical: "top",
    },
  });
}
