import {
  ArrowsClockwise,
  Bell,
  Buildings,
  CaretRight,
  CaretUp,
  Cat,
  CheckCircle,
  CloudSlash,
  Dog,
  FirstAidKit,
  GearSix,
  Heart,
  Hourglass,
  House,
  MagnifyingGlass,
  MapPin,
  MapTrifold,
  MinusCircle,
  Moon,
  NavigationArrow,
  PaperPlaneRight,
  PawPrint,
  Plus,
  ShieldCheck,
  SignIn,
  SignOut,
  Sliders,
  Sun,
  Translate,
  User,
  WarningCircle,
  X,
  XCircle,
  type IconWeight,
} from "phosphor-react-native";

const iconMap = {
  home: { Icon: House, weight: "fill" },
  "home-outline": { Icon: House, weight: "regular" },
  search: { Icon: MagnifyingGlass, weight: "fill" },
  "search-outline": { Icon: MagnifyingGlass, weight: "regular" },
  heart: { Icon: Heart, weight: "fill" },
  "heart-outline": { Icon: Heart, weight: "regular" },
  paw: { Icon: PawPrint, weight: "fill" },
  "paw-outline": { Icon: PawPrint, weight: "regular" },
  settings: { Icon: GearSix, weight: "fill" },
  "settings-outline": { Icon: GearSix, weight: "regular" },
  "first-aid": { Icon: FirstAidKit, weight: "fill" },
  "first-aid-outline": { Icon: FirstAidKit, weight: "regular" },
  "chevron-forward": { Icon: CaretRight, weight: "bold" },
  "chevron-up": { Icon: CaretUp, weight: "bold" },
  close: { Icon: X, weight: "bold" },
  "close-circle-outline": { Icon: XCircle, weight: "regular" },
  send: { Icon: PaperPlaneRight, weight: "fill" },
  "checkmark-circle-outline": { Icon: CheckCircle, weight: "regular" },
  "log-in-outline": { Icon: SignIn, weight: "regular" },
  "log-out-outline": { Icon: SignOut, weight: "regular" },
  "person-outline": { Icon: User, weight: "regular" },
  person: { Icon: User, weight: "fill" },
  "notifications-outline": { Icon: Bell, weight: "regular" },
  add: { Icon: Plus, weight: "bold" },
  "location-outline": { Icon: MapPin, weight: "regular" },
  map: { Icon: MapTrifold, weight: "regular" },
  "navigate-outline": { Icon: NavigationArrow, weight: "regular" },
  "business-outline": { Icon: Buildings, weight: "regular" },
  "options-outline": { Icon: Sliders, weight: "regular" },
  "remove-circle-outline": { Icon: MinusCircle, weight: "regular" },
  "warning-outline": { Icon: WarningCircle, weight: "regular" },
  "alert-circle-outline": { Icon: WarningCircle, weight: "regular" },
  "shield-checkmark": { Icon: ShieldCheck, weight: "fill" },
  sunny: { Icon: Sun, weight: "fill" },
  moon: { Icon: Moon, weight: "fill" },
  "language-outline": { Icon: Translate, weight: "regular" },
  cat: { Icon: Cat, weight: "fill" },
  dog: { Icon: Dog, weight: "fill" },
  "cloud-offline-outline": { Icon: CloudSlash, weight: "regular" },
  "sync-outline": { Icon: ArrowsClockwise, weight: "regular" },
  "hourglass-outline": { Icon: Hourglass, weight: "regular" },
} as const;

export type IconName = keyof typeof iconMap;

export function AppIcon({
  name,
  size,
  color,
}: {
  name: IconName;
  size: number;
  color: string;
}) {
  const { Icon, weight } = iconMap[name];
  return <Icon size={size} color={color} weight={weight as IconWeight} />;
}
